### ISSUE TITLE
Output in file

### ISSUE THREAD

**Issue by SenadSuljkanovic** [ArifCengic/TopTen#4]
TopTenApp bi trebao zapisati datum i vrijeme te vrijednosti koje je nasao, u neki "file", te nakon svakog novog pokretanja prikazati "history" tih vrijednosti.

**Comment by ArifCengic** [comment]
FileName - "TopTen" + YYMMDD HH:mm:SS
XML File Format

<App>
<WebSites>
<WebSite>
<Url> klix.ba </Url>
<GetHtmlTiming> 125 </GetHtmlTiming>
<ProcessingTime> 70 </ProcessingTime>
<Words>
<Word> danas </Word>
<Word> avion </Word>
<Word> auto </Word>
</Words>
<WebSite>

**Comment by Malajac** [comment]
Vidim da je issue zatvoren. Je li ovo treba raditi?

**Comment by Malajac** [comment]
{
                    DateTime currentDT = DateTime.Now;
                    string currentDTString = currentDT.ToString("yyyyMMdd_HHmmss") + ".xml";
                    string histogramFileName = "TopTen" + currentDTString;
                    XmlWriterSettings settings = new XmlWriterSettings();
                    settings.Indent = true;
                    XmlWriter writer = XmlWriter.Create(histogramFileName, settings);
                    DataContractSerializer serializer = new DataContractSerializer(typeof(Dictionary<string, int>));
                    serializer.WriteObject(writer, res5);
                    writer.Close();

                    //XmlReader reader = XmlReader.Create(histogramFileName);
                    //serializer = new DataContractSerializer(typeof(Dictionary<string, int>));
                    //res5 = (Dictionary<string, int>)serializer.ReadObject(reader);
                    //reader.Close();
                }
